version: "3.3"

services:
  pig:
    image: pig
    container_name: 'pig'
    ports:
      - "8000:8000"

  redis:
    image: redis:latest

  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
